import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { AppError, type Proposal } from './model';
export type EntityTable='clients'|'pricing_items'|'templates'|'content_library';
export interface Repository { get(id:string):Promise<Proposal|null>; list():Promise<Proposal[]>; save(p:Proposal,expected:number):Promise<void>; entities<T>(table:EntityTable):Promise<T[]>; put<T extends {id:string}>(table:EntityTable,entity:T):Promise<void>; }
export class MemoryRepository implements Repository { rows=new Map<string,Proposal>(); catalog=new Map<EntityTable,Map<string,unknown>>();async get(id:string){return structuredClone(this.rows.get(id)??null)}async list(){return structuredClone([...this.rows.values()])}async save(p:Proposal,expected:number){if((this.rows.get(p.id)?.revision??-1)!==expected)throw new AppError(409,'Proposal changed; reload and try again');this.rows.set(p.id,structuredClone(p));}async entities<T>(table:EntityTable){return structuredClone([...(this.catalog.get(table)?.values()??[])]) as T[]}async put<T extends {id:string}>(table:EntityTable,entity:T){if(!this.catalog.has(table))this.catalog.set(table,new Map());this.catalog.get(table)!.set(entity.id,structuredClone(entity));}}
// Local development only, single Node process. Production always uses database CAS.
export class LocalRepository extends MemoryRepository {private ready:Promise<void>;private tail:Promise<unknown>=Promise.resolve();constructor(private dir:string){super();this.ready=this.load()}private async load(){try{const d=JSON.parse(await readFile(join(this.dir,'db.json'),'utf8'));this.rows=new Map(d.rows);this.catalog=new Map(d.catalog.map(([k,v]:[EntityTable,[string,unknown][]])=>[k,new Map(v)]));}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}}private async persist(){await mkdir(this.dir,{recursive:true});await writeFile(join(this.dir,'db.tmp'),JSON.stringify({rows:[...this.rows],catalog:[...this.catalog].map(([k,v])=>[k,[...v]])}),{mode:0o600});await rename(join(this.dir,'db.tmp'),join(this.dir,'db.json'));}override async get(id:string){await this.ready;return super.get(id)}override async list(){await this.ready;return super.list()}override async entities<T>(t:EntityTable){await this.ready;return super.entities<T>(t)}override async save(p:Proposal,e:number){await this.ready;const run=this.tail.then(async()=>{await super.save(p,e);await this.persist()});this.tail=run.catch(()=>{});await run}override async put<T extends {id:string}>(t:EntityTable,e:T){await this.ready;const run=this.tail.then(async()=>{await super.put(t,e);await this.persist()});this.tail=run.catch(()=>{});await run}}
export class SupabaseRepository implements Repository {constructor(public db:SupabaseClient){}async get(id:string){const {data,error}=await this.db.from('proposals').select('state').eq('id',id).maybeSingle();if(error)throw error;return data?.state as Proposal??null}async list(){const all:Proposal[]=[];for(let from=0;;from+=500){const {data,error}=await this.db.from('proposals').select('state').order('id').range(from,from+499);if(error)throw error;all.push(...data.map(x=>x.state as Proposal));if(data.length<500)return all;}}async save(p:Proposal,expected:number){const {error}=await this.db.rpc('save_proposal',{document:p,expected_revision:expected});if(error){if(error.code==='40001'||error.code==='23505')throw new AppError(409,'Proposal changed; reload and try again');throw error;}}async entities<T>(table:EntityTable){const {data,error}=await this.db.from(table).select('data');if(error)throw error;return data.map(x=>x.data as T)}async put<T extends {id:string}>(table:EntityTable,entity:T){const {error}=await this.db.from(table).upsert({id:entity.id,data:entity});if(error)throw error;}}
export function supabase(){if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY)throw new Error('Supabase credentials required');return createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})}
export async function mutate(repo:Repository,id:string,fn:(p:Proposal)=>void){for(let attempt=0;attempt<6;attempt++){const p=await repo.get(id);if(!p)throw new AppError(404,'Proposal not found');const revision=p.revision;fn(p);p.revision=revision+1;p.updated_at=new Date().toISOString();try{await repo.save(p,revision);return p;}catch(e){if(!(e instanceof AppError)||e.status!==409||attempt===5)throw e;}}throw new Error('Unreachable');}
